# Generated by Django 3.1.3 on 2020-11-24 11:36

import address.validation
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line', models.CharField(max_length=50, validators=[address.validation.Validation.symbolValidation])),
                ('postal_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Postal code must be contains exactly 5 digits', regex='^\\d{5}$')])),
                ('country', models.CharField(max_length=50, validators=[address.validation.Validation.symbolValidation])),
                ('city', models.CharField(max_length=50, validators=[address.validation.Validation.symbolValidation])),
                ('fax_number', models.CharField(max_length=13, validators=[address.validation.Validation.numberValidation])),
                ('phone_number', models.CharField(max_length=13, validators=[address.validation.Validation.numberValidation])),
            ],
        ),
    ]
