# Generated by Django 3.1.3 on 2020-11-17 11:18

import address.validation
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line',
            field=models.CharField(max_length=50, validators=[address.validation.Validation.symbolValidation]),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=50, validators=[address.validation.Validation.symbolValidation]),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=50, validators=[address.validation.Validation.symbolValidation]),
        ),
        migrations.AlterField(
            model_name='address',
            name='fax_number',
            field=models.CharField(max_length=13, validators=[address.validation.Validation.numberValidation]),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[address.validation.Validation.numberValidation]),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Postal code must be contains exactly 5 digits', regex='^\\d{5}$')]),
        ),
    ]
