# Generated by Django 3.1.3 on 2020-11-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='address',
            name='fax_number',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(max_length=17),
        ),
    ]
