# Generated by Django 3.1.3 on 2020-11-16 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(message='Dont use symbol', regex='')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Dont use symbol', regex='')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Dont use symbol', regex='')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='fax_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+123456789012'.", regex='^\\+?1?\\d{12,15}$')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+123456789012'.", regex='^\\+?1?\\d{12,15}$')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Postal code must be contains exactly 5 digits', regex='^\\d{5}$')]),
        ),
    ]
