# Generated by Django 3.1.3 on 2020-11-23 23:15

import modules.address.validation
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line', models.CharField(max_length=50, validators=[address.validation.Validation.symbolValidation])),
                ('postal_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Postal code must be contains exactly 5 digits', regex='^\\d{5}$')])),
                ('country', models.CharField(max_length=50, validators=[address.validation.Validation.symbolValidation])),
                ('city', models.CharField(max_length=50, validators=[address.validation.Validation.symbolValidation])),
                ('fax_number', models.CharField(max_length=13, validators=[address.validation.Validation.numberValidation])),
                ('phone_number', models.CharField(max_length=13, validators=[address.validation.Validation.numberValidation])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ')),
            ],
        ),
    ]
