# Generated by Django 3.1.3 on 2020-12-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
